<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('transactions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')
                ->nullable()
                ->constrained('users')
                ->onDelete('set null');

            $table->decimal('amount', 10, 2);
            $table->string('receipt_image')->nullable();

            $table->timestamp('paid_at')->nullable()
                ->comment('Timestamp when the transaction was marked as paid');

            $table->string('authority')
                ->nullable()
                ->unique()
                ->comment('Authority code generated by the payment gateway');

            $table->string('transactionID')
                ->nullable()
                ->unique()
                ->comment('Tracking code for the transaction');


            // Payment method as ENUM
            $table->enum('payment_method', [
                'online',
                'atm',
                'pos',
                'paycheck',
                'wallet'
            ])->default('online');

            // Transaction status as ENUM
            $table->enum('transaction_status', [
                'transferred_to_pay',
                'unsuccessful',
                'successful',
                'pending',
                'archived_successful',
                'unpaid',
                'suspended',
                'organizational_unpaid'
            ])->default('unpaid')
                ->comment('Status of the transaction (e.g., pending, successful)');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('transactions');
    }
};
